services:
  aivideomaker-api:
    image: aivideomaker-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: develop
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: develop
    ports:
      - 3000:3000
