version: '3.4'

services:
  aivideomaker:
    image: aivideomaker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: .
          target: /
    ports:
      - 3000:3000
    command: ['npm', 'start:dev']
